export const citys = [
  { "id": "a02", "name": "台北" },
  { "id": "a01", "name": "基隆" },
  { "id": "a03", "name": "桃園" },
  { "id": "a35", "name": "新竹" },
  { "id": "a37", "name": "苗栗" },
  { "id": "a49", "name": "南投" },
  { "id": "a39", "name": "宜蘭" },
  { "id": "a04", "name": "台中" },
  { "id": "a47", "name": "彰化" },
  { "id": "a45", "name": "雲林" },
  { "id": "a05", "name": "嘉義" },
  { "id": "a06", "name": "台南" },
  { "id": "a07", "name": "高雄" },
  { "id": "a87", "name": "屏東" },
  { "id": "a38", "name": "花蓮" },
  { "id": "a89", "name": "台東" },
  { "id": "a69", "name": "澎湖" },
  { "id": "a68", "name": "金門" }
]