["Anteater", "Bear", "Bird", "Bull", "Cat", "Cub", "Chicken", "Cow", "Alligator", "Deer", "Dog", "Duck", "Elephant", "Frog", "Goat", "Gorilla", "Hamster", "Hippo", "Horse", "Koala", "Kangaroo", "Lion", "Monkey", "Mouse", "Octopus", "Ostrich", "Eagle", "Penguin", "Pig", "Rabbit", "Rhino", "Sheep", "Squirrel", "Tiger", "Wolf"]

export function translateSpecies(key: string) {
  switch (key) {
    case 'Anteater':
      return '食蟻獸'
    case 'Bear':
      return '大熊'
    case 'Bird':
      return '鳥'
    case 'Bull':
      return '公牛'
    case 'Cat':
      return '貓'
    case 'Cub':
      return '小熊'
    case 'Chicken':
      return '雞'
    case 'Cow':
      return '乳牛'
    case 'Alligator':
      return '鱷魚'
    case 'Deer':
      return '鹿'
    case 'Dog':
      return '狗'
    case 'Duck':
      return '鴨'
    case 'Elephant':
      return '象'
    case 'Frog':
      return '蛙'
    case 'Goat':
      return '山羊'
    case 'Gorilla':
      return '猩猩'
    case 'Hamster':
      return '倉鼠'
    case 'Hippo':
      return '河馬';
    case 'Horse':
      return '馬';
    case 'Koala':
      return '無尾熊';
    case 'Kangaroo':
      return '袋鼠';
    case 'Lion':
      return '獅';
    case 'Monkey':
      return '猴';
    case 'Mouse':
      return '鼠';
    case 'Monkey':
      return '猴';
    case 'Octopus':
      return '章魚';
    case 'Eagle':
      return '鷹';
    case 'Penguin':
      return '企鵝';
    case 'Pig':
      return '豬';
    case 'Rabbit':
      return '兔';
    case 'Rhino':
      return '犀牛';
    case 'Sheep':
      return '綿羊';
    case 'Squirrel':
      return '松鼠';
    case 'Tiger':
      return '虎';
    case 'Wolf':
      return '狼';
    case 'Ostrich':
      return '鴕鳥'
    default:
      return key;
  }
}